// AcademyData.jsx - BASE DE DATOS PROFESIONAL DE CLASSCODE ACADEMY

export const ACADEMY_DB = {
  "Generico": [
    { q: "PUNTUALIDAD: ¿CUÁNDO DEBES ESTAR EN EL LUGAR?", a: ["A LA HORA DE INICIO", "15-30 MIN ANTES", "10 MIN DESPUÉS"], correct: 1 },
    { q: "BACKUP: ¿CUÁL ES EL PROTOCOLO DE SEGURIDAD?", a: ["AL LLEGAR A CASA", "DOBLE BACKUP AL MOMENTO", "MAÑANA POR LA NUBE"], correct: 1 },
    { q: "VESTIMENTA: ¿QUÉ USAR EN EVENTO 'BLACK TIE'?", a: ["ROPA INFORMAL", "TOTAL BLACK DISCRETO", "REMERAS CON LOGO"], correct: 1 },
    { q: "COMPORTAMIENTO: PEDIDO DE ÚLTIMO MOMENTO:", a: ["NEGARSE", "RESOLVER Y COBRAR LUEGO", "HACERLO DE MALA GANA"], correct: 1 }
  ],
  "fotografia_intro": [
    { q: "¿CUÁL ES EL PROPÓSITO CENTRAL DE LA ETAPA INICIAL EN SET?", a: ["IMPROVISAR SOBRE LA MARCHA", "RECONOCIMIENTO DEL ESPACIO Y PLANIFICACIÓN", "ESPERAR INDICACIONES"], correct: 1 },
    { q: "¿QUÉ FACTOR ES INNEGOCIABLE EN LA COMUNICACIÓN CON EL EQUIPO?", a: ["CLARIDAD Y RIGOR TÉCNICO", "VELOCIDAD SIN REVISAR", "USAR FILTROS RÁPIDOS"], correct: 0 },
    { q: "¿CÓMO SE DEBE GESTIONAR EL MATERIAL BRUTO AL FINALIZAR LA SESIÓN?", a: ["GUARDARLO PARA MAÑANA", "APLICAR PROTOCOLO DE DOBLE BACKUP INMEDIATO", "SUBIRLO A REDES DIRECTO"], correct: 1 }
  ],
  "fotografia_triangulo": [
    { q: "¿QUÉ AJUSTE MODIFICA LA PROFUNDIDAD DE CAMPO Y EL BOKEH?", a: ["VELOCIDAD DE OBTURACIÓN", "APERTURA DEL DIAFRAGMA", "SENSIBILIDAD ISO"], correct: 1 },
    { q: "¿CÓMO EVITAS EL MOVIMIENTO MOVIDO EN FOTOS DE ACCIÓN?", a: ["BAJANDO EL ISO", "AUMENTANDO LA VELOCIDAD (1/500+)", "CERRANDO EL DIAFRAGMA"], correct: 1 },
    { q: "SI SUBO EL ISO PARA GANAR LUZ, ¿CUÁL ES EL RIESGO?", a: ["PERDER ENFOQUE", "APARICIÓN DE RUIDO DIGITAL", "CAMBIO DE COLOR"], correct: 1 }
  ],
  "Audiovisual": [
    { q: "¿FPS PARA UN LOOK CINEMATOGRÁFICO ESTÁNDAR?", a: ["60 FPS", "24 FPS", "120 FPS"], correct: 1 },
    { q: "¿PARA QUÉ SE UTILIZA UN PERFIL DE COLOR LOG?", a: ["YA VIENE EDITADO", "MAYOR RANGO DINÁMICO", "AHORRAR MEMORIA"], correct: 1 },
    { q: "¿QUÉ ACCESORIO ES VITAL PARA MOVIMIENTOS FLUIDOS?", a: ["FILTRO ND", "GIMBAL / ESTABILIZADOR", "TRÍPODE FIJO"], correct: 1 }
  ],
  "Modelo": [
    { q: "¿QUÉ ES UN CASTING REEL?", a: ["VIDEO DE PRESENTACIÓN", "BOOK DE FOTOS", "CONTRATO"], correct: 0 },
    { q: "¿CÓMO POSAR PARA UNA EDITORIAL DE VANGUARDIA?", a: ["SONRISA A CÁMARA", "LÍNEAS CORPORALES Y ACTITUD", "POSES ESTÁTICAS"], correct: 1 }
  ],
  "Escénico": [
    { q: "¿QUÉ ES FUNDAMENTAL EN LA EXPRESIÓN CORPORAL PARA CÁMARA?", a: ["ESTAR RÍGIDO", "CONCIENCIA ESPACIAL Y LÍNEAS CORPORALES", "MIRAR SIEMPRE AL PISO"], correct: 1 },
    { q: "¿CÓMO SE MANEJA LA TÉCNICA ACTORAL FRENTE A UN MARCO TÉCNICO?", a: ["IGNORAR LAS LUCES", "ADAPTARSE AL ENCUADRE Y MARCAS EN PISO", "MOVERSE SIN AVISAR"], correct: 1 }
  ],
  "Digital": [
    { q: "¿CUÁL ES EL ENFOQUE PRINCIPAL DE CONTENIDO UGC?", a: ["ANUNCIO TRADICIONAL DE TV", "AUTENTICIDAD Y CONEXIÓN DIRECTA CON LA COMUNIDAD", "VIDEOS MUDOS"], correct: 1 },
    { q: "¿QUÉ MÉTRICA DEFINE EL NIVEL DE INTERACCIÓN REAL?", a: ["IMPRESIONES TOTALES", "ENGAGEMENT RATE", "CANTIDAD DE SEGUIDORES"], correct: 1 }
  ],
  "Show": [
    { q: "¿CUALIDAD VITAL DEL ANIMADOR O ARTISTA EN VIVO?", a: ["MANEJO DE ENERGÍA Y LIDERAZGO DE ESCENA", "VOZ BAJA", "AISLARSE DEL PÚBLICO"], correct: 0 },
    { q: "¿CÓMO SE RESPONDE ANTE UN DESPERTECTO TÉCNICO EN VIVO?", a: ["PARAR EL SHOW Y GRITAR", "IMPROVISAR CON SEGURIDAD Y FLUIDEZ", "ABANDONAR EL ESCENARIO"], correct: 1 }
  ],
  "Producción / Dirección": [
    { q: "¿QUÉ DOCUMENTO ORGANIZA EL ORDEN DE RODAJE HORA POR HORA?", a: ["EL PRESUPUESTO", "LA ORDEN DEL DÍA / PLAN DE RODAJE", "EL GUION TÉCNICO SOLAMENTE"], correct: 1 },
    { q: "¿QUIÉN ES EL RESPONSABLE GLOBAL DE LA LOGÍSTICA EN SET?", a: ["EL DIRECTOR DE FOTOGRAFÍA", "EL PRODUCTOR EJECUTIVO / JEFE DE PRODUCCIÓN", "EL ACTOR PRINCIPAL"], correct: 1 }
  ],
  "Makeup / Pelo": [
    { q: "¿CÓMO EVITAR EL BRILLO NO DESEADO POR FLASH EN PIEL?", a: ["POLVOS TRASLÚCIDOS", "ILUMINADOR LÍQUIDO", "GLOSS EXCESIVO"], correct: 0 },
    { q: "¿USO OBLIGATORIO ANTES DE PLANCHA O BUCLERA EN PELO?", a: ["LACA FUERTE", "PROTECTOR TÉRMICO", "AGUA PURA"], correct: 1 },
    { q: "¿QUÉ NORMA DE HIGIENE ES INNEGOCIABLE?", a: ["USO DE ESPÁTULAS Y PALETAS (NO APLICAR DIRECTO)", "USAR LOS DEDOS", "COMPARTIR PRODUCTOS"], correct: 0 }
  ],
  "Estilismo / Moda": [
    { q: "¿QUÉ SE HACE EN UNA SESIÓN DE FITTING?", a: ["PRUEBA Y AJUSTE DE PRENDAS CON EL TALENTO", "COMPRAR ROPA NUEVA", "CAMINAR POR LA PASARELA"], correct: 0 },
    { q: "¿PARA QUÉ SIRVE EL MOODBOARD DE VESTUARIO?", a: ["DEFINIR EL CONCEPTO VISUAL Y GAMA DE COLORES", "PAGAR FACTURAS", "LISTAR TALLES"], correct: 0 }
  ],
  "Diseño / Arte": [
    { q: "¿SISTEMA DE COLOR CORRECTO PARA PIEZAS IMPRESAS?", a: ["RGB", "CMYK", "HEX"], correct: 1 },
    { q: "¿POR QUÉ SE UTILIZAN VECTORES EN DISEÑO DE IDENTIDAD?", a: ["ESCALAN INFINITAMENTE SIN PERDER CALIDAD", "SON MÁS PESADOS", "TIENEN MÁS EFECTOS"], correct: 0 }
  ],
  "DJ / Sonido": [
    { q: "¿QUÉ ES EL BEATMATCHING?", a: ["SINCRONIZAR RITMOS Y TEMPOS", "SUBIR EL VOLUMEN AL MÁXIMO", "CAMBIAR DE CANCIÓN"], correct: 0 },
    { q: "¿QUÉ INDICA EL VÚMETRO EN ROJO CONSTANTE?", a: ["POTENCIA ÓPTIMA", "DISTORSIÓN Y DAÑO (CLIPPING)", "SEÑAL BAJA"], correct: 1 }
  ],
  "Catering / Barra": [
    { q: "¿CARNET O CURSO INDISPENSABLE PARA MANIPULACIÓN DE ALIMENTOS?", a: ["CURSO DE MANIPULACIÓN VIGENTE", "DNI", "SEGURO DE VIDA"], correct: 0 },
    { q: "¿PARA QUÉ SIRVE UN JIGGER EN BARRA?", a: ["MEDICIÓN EXACTA DE BEBIDAS", "LIMPIAR LA COCTELERA", "MOLER HIELO"], correct: 0 }
  ],
  "Planner / Eventos": [
    { q: "¿QUÉ ES EL TIMELINE O CRONOGRAMA DE UN EVENTO?", a: ["LA LISTA DE INVITADOS", "LA GUÍA MINUTO A MINUTO DE CADA HIT DEL EVENTO", "EL PLANO DEL LUGAR"], correct: 1 },
    { q: "¿CUÁL ES LA CLAVE ANTE UN CAMBIO DE ÚLTIMO MOMENTO EN EVENTOS?", a: ["BLOQUEARSE", "PLAN DE CONTINGENCIA Y RESOLUCIÓN ÁGIL", "CANCELAR TODO"], correct: 1 }
  ],
  "Técnica / Iluminación": [
    { q: "¿TEMPERATURA DE COLOR ESTÁNDAR PARA LUZ DÍA (DAYLIGHT)?", a: ["3200K", "5600K", "10000K"], correct: 1 },
    { q: "¿QUÉ CONECTOR SE UTILIZA PARA SEÑALES DE AUDIO PROFESIONAL Y DMX?", a: ["USB", "PLUG COMÚN", "XLR"], correct: 2 }
  ],
  "Agencia": [
    { q: "¿CUÁL ES EL ROL PRINCIPAL DE UNA AGENCIA DE TALENTOS?", a: ["REPRESENTACIÓN, GESTIÓN COMERCIAL Y VINCULACIÓN", "SOLO COBRAR COMISIONES", "DISEÑAR ROPA"], correct: 0 },
    { q: "¿QUÉ ES UN COMPOSITE CARD (COMPCARD)?", a: ["TARJETA DE PRESENTACIÓN CON FOTOS Y MEDIDAS DEL TALENTO", "UN CONTRATO DIGITAL", "UNA FACTURA"], correct: 0 }
  ],
  "Locaciones": [
    { q: "¿QUÉ ES UN SCOUTING TÉCNICO DE LOCACIÓN?", a: ["BUSCAR ACTORES POR LA CALLE", "VISITA Y EVALUACIÓN TÉCNICA DE ESPACIOS Y LUZ", "PEDIR CATERING"], correct: 1 },
    { q: "¿POR QUÉ ES VITAL REVISAR LA TOMA ELÉCTRICA DEL LUGAR?", a: ["PARA CARGAR CELULARES", "POR LA POTENCIA Y FASES DISPONIBLES PARA EQUIPOS PESADOS", "PARA EL WI-FI"], correct: 1 }
  ]
};