// AcademyData.jsx - BASE DE DATOS PROFESIONAL DE CLASSCODE ACADEMY

export const ACADEMY_DB = {
  "Generico": [
    { q: "PUNTUALIDAD: ¿CUÁNDO DEBES ESTAR EN EL LUGAR?", a: ["A LA HORA DE INICIO", "15-30 MIN ANTES", "10 MIN DESPUÉS"], correct: 1 },
    { q: "BACKUP: ¿CUÁL ES EL PROTOCOLO DE SEGURIDAD?", a: ["AL LLEGAR A CASA", "DOBLE BACKUP AL MOMENTO", "MAÑANA POR LA NUBE"], correct: 1 },
    { q: "VESTIMENTA: ¿QUÉ USAR EN EVENTO 'BLACK TIE'?", a: ["ROPA INFORMAL", "TOTAL BLACK DISCRETO", "REMERAS CON LOGO"], correct: 1 },
    { q: "COMPORTAMIENTO: PEDIDO DE ÚLTIMO MOMENTO:", a: ["NEGARSE", "RESOLVER Y COBRAR LUEGO", "HACERLO DE MALA GANA"], correct: 1 }
  ],
  "Fotografía": [
    { q: "¿QUÉ FORMATO DE ARCHIVO ES OBLIGATORIO PARA EDICIÓN PRO?", a: ["JPG EN ALTA", "RAW (CRUDO)", "PNG"], correct: 1 },
    { q: "¿QUÉ LENTE ES IDEAL PARA RETRATOS SIN DISTORSIÓN?", a: ["GRAN ANGULAR 16MM", "TELEOBJETIVO 85MM", "OJO DE PEZ"], correct: 1 },
    { q: "¿CÓMO EVITAS EL MOVIMIENTO MOVIDO SIN USAR FLASH?", a: ["BAJANDO EL ISO", "AUMENTANDO LA VELOCIDAD", "CERRANDO EL DIAFRAGMA"], correct: 1 },
    { q: "¿QUÉ ELEMENTO COMPONE LA REGLA DE LOS TERCIOS?", a: ["EL BALANCE DE BLANCOS", "DOS LÍNEAS HORIZONTALES Y DOS VERTICALES", "EL ENFOQUE AL CENTRO"], correct: 1 }
  ],
  "fotografia_triangulo": [
    { q: "¿QUÉ AJUSTE MODIFICA LA PROFUNDIDAD DE CAMPO Y EL BOKEH?", a: ["VELOCIDAD DE OBTURACIÓN", "APERTURA DEL DIAFRAGMA", "SENSIBILIDAD ISO"], correct: 1 },
    { q: "¿CÓMO EVITAS EL MOVIMIENTO MOVIDO EN FOTOS DE ACCIÓN?", a: ["BAJANDO EL ISO", "AUMENTANDO LA VELOCIDAD (1/500+)", "CERRANDO EL DIAFRAGMA"], correct: 1 },
    { q: "SI SUBO EL ISO PARA GANAR LUZ, ¿CUÁL ES EL RIESGO?", a: ["PERDER ENFOQUE", "APARICIÓN DE RUIDO DIGITAL", "CAMBIO DE COLOR"], correct: 1 }
  ],
  "Video / Filmmaker": [
    { q: "¿FPS PARA UN LOOK CINEMATOGRÁFICO ESTÁNDAR?", a: ["60 FPS", "24 FPS", "120 FPS"], correct: 1 },
    { q: "¿PARA QUÉ SE UTILIZA UN PERFIL DE COLOR LOG?", a: ["YA VIENE EDITADO", "MAYOR RANGO DINÁMICO", "AHORRAR MEMORIA"], correct: 1 },
    { q: "¿QUÉ ACCESORIO ES VITAL PARA MOVIMIENTOS FLUIDOS?", a: ["FILTRO ND", "GIMBAL / ESTABILIZADOR", "TRÍPODE FIJO"], correct: 1 },
    { q: "¿REGLA DE OBTURACIÓN PARA VIDEO (180 DEGREES)?", a: ["IGUAL A LOS FPS", "DOBLE DE LOS FPS", "MITAD DE LOS FPS"], correct: 1 }
  ],
  "DJ / Sonido": [
    { q: "¿QUÉ ES EL BEATMATCHING?", a: ["SINCRONIZAR RITMOS", "SUBIR EL VOLUMEN", "CAMBIAR DE CANCIÓN"], correct: 0 },
    { q: "¿QUÉ INDICA EL ROJO CONSTANTE EN EL VÚMETRO?", a: ["POTENCIA ÓPTIMA", "DISTORSIÓN Y DAÑO (CLIPPING)", "FALTA DE SEÑAL"], correct: 1 },
    { q: "¿PARA QUÉ SIRVE EL FILTRO PASA-ALTOS (HPF)?", a: ["SUBIR GRAVES", "LIMPIAR FRECUENCIAS BAJAS", "MUDAR EL AUDIO"], correct: 1 },
    { q: "¿QUÉ ES UN ARCHIVO DE AUDIO LOSSLESS?", a: ["MP3 COMPRIMIDO", "WAV / AIFF SIN PÉRDIDA", "SPOTIFY LINK"], correct: 1 }
  ],
  "Modelo / Presencia": [
    { q: "¿QUÉ ES UN CASTING REEL?", a: ["VIDEO DE PRESENTACIÓN", "BOOK DE FOTOS", "CONTRATO"], correct: 0 },
    { q: "¿CÓMO POSAR PARA UNA EDITORIAL DE VANGUARDIA?", a: ["SONRISA A CÁMARA", "LÍNEAS CORPORALES Y ACTITUD", "POSES ESTÁTICAS"], correct: 1 },
    { q: "¿QUÉ ES EL LOOKBOOK EN UN RODAJE?", a: ["GUÍA DE POSES Y VESTUARIO", "LISTA DE PRECIOS", "MENÚ DE CATERING"], correct: 0 },
    { q: "¿MÁS IMPORTANTE ANTES DE IR A SET?", a: ["LLEVAR JOYAS", "ESTUDIAR EL MOODBOARD", "IR SIN DORMIR"], correct: 1 }
  ],
  "Locaciones": [
    { q: "¿QUÉ ES EL SCOUTING TÉCNICO?", a: ["BUSCAR ACTORES", "VISITAR Y EVALUAR EL LUGAR", "PEDIR COMIDA"], correct: 1 },
    { q: "¿POR QUÉ ES CRUCIAL EL ORIENTACIÓN DEL SOL?", a: ["POR EL CALOR", "POR EL PLANO DE LUCES", "POR EL WI-FI"], correct: 1 },
    { q: "¿REQUISITO ELÉCTRICO PARA EQUIPOS PESADOS?", a: ["ENCHUFES COMUNES", "POTENCIA Y FASES DISPONIBLES", "ALARGUES LARGOS"], correct: 1 }
  ],
  "Makeup / Pelo": [
    { q: "¿CÓMO EVITAR EL BRILLO POR FLASH EN PIEL?", a: ["POLVOS TRASLÚCIDOS", "ILUMINADOR LÍQUIDO", "GLOSS"], correct: 0 },
    { q: "¿FUNCIÓN DEL CORRECTOR COMPLEMENTARIO (NARANJA)?", a: ["TAPAR GRANITOS", "NEUTRALIZAR OJERAS AZULES", "DAR LUZ"], correct: 1 },
    { q: "¿USO OBLIGATORIO ANTES DE PLANCHA O BUCLERA?", a: ["LACA FUERTE", "PROTECTOR TÉRMICO", "AGUA"], correct: 1 },
    { q: "¿QUÉ ES EL HIGIENE PROFESIONAL EN MAQUILLAJE?", a: ["LIMPIAR AL FINAL", "USO DE ESPÁTULAS Y MEZCLADORES", "DEDOS LIMPIOS"], correct: 1 }
  ],
  "Estilismo / Moda": [
    { q: "¿QUÉ SE HACE EN EL FITTING?", a: ["PRUEBA Y AJUSTE DE PRENDAS", "COMPRAR ROPA", "CAMINAR"], correct: 0 },
    { q: "¿PARA QUÉ SIRVE EL MOODBOARD DE VESTUARIO?", a: ["PAGAR FACTURAS", "DEFINIR CONCEPTO VISUAL", "LISTA DE TALLES"], correct: 1 },
    { q: "¿QUÉ ES UN OUTFIT STATEMENT?", a: ["ROPA BÁSICA", "PIEZA CENTRAL LLAMATIVA", "ROPA DEPORTIVA"], correct: 1 }
  ],
  "Diseño Gráfico": [
    { q: "¿SISTEMA DE COLOR PARA IMPRENTA?", a: ["RGB", "CMYK", "HEX"], correct: 1 },
    { q: "¿POR QUÉ USAR VECTORES PARA LOGOS?", a: ["SON MÁS LINDOS", "ESCALAN SIN PERDER CALIDAD", "PESAN MENOS"], correct: 1 },
    { q: "¿QUÉ ES EL KERNING?", a: ["TIPO DE COLOR", "ESPACIO ENTRE LETRAS", "TAMAÑO PAPEL"], correct: 1 }
  ],
  "Catering / Barra": [
    { q: "¿CARNET INDISPENSABLE PARA TRABAJAR?", a: ["CURSO DE MANIPULACIÓN", "DNI", "SEGURO"], correct: 0 },
    { q: "¿QUÉ ES EL SERVICIO FINGER FOOD?", a: ["COMIDA AL PLATO", "BOCADOS PARA LA MANO", "POSTRES"], correct: 1 },
    { q: "¿PARA QUÉ SIRVE EL JIGGER EN BARRA?", a: ["LIMPIAR", "MEDICIÓN EXACTA", "BATIR"], correct: 1 }
  ],
  "Animación / Show": [
    { q: "¿CUALIDAD VITAL DEL ANIMADOR?", a: ["VESTUARIO", "MANEJO DE ENERGÍA Y PÚBLICO", "VOZ BAJA"], correct: 1 },
    { q: "¿CÓMO REACCIONAR ANTE UN IMPREVISTO?", a: ["PARAR EL SHOW", "IMPROVISAR CON SEGURIDAD", "ENOJARSE"], correct: 1 },
    { q: "¿ELEMENTO DE SEGURIDAD EN SHOW DE FX?", a: ["CINTA", "EXTINTOR Y PROTOCOLO", "AGUA"], correct: 1 }
  ],
  "Ambientación": [
    { q: "¿QUÉ ES EL LAYOUT DE UN EVENTO?", a: ["LAS FLORES", "MAPA DE DISTRIBUCIÓN", "LOS COLORES"], correct: 1 },
    { q: "¿PARA QUÉ SE USAN LOS PARLEDS?", a: ["PARA LEER", "ILUMINACIÓN ARQUITECTÓNICA", "BUFFET"], correct: 1 },
    { q: "¿CARACTERÍSTICA DE TELA IGNÍFUGA?", a: ["ES BRILLANTE", "NO PROPAGA EL FUEGO", "ES ELÁSTICA"], correct: 1 }
  ],
  "Técnica / Ilum.": [
    { q: "¿TEMPERATURA DE LUZ DÍA ESTÁNDAR?", a: ["3200K", "5600K", "10000K"], correct: 1 },
    { q: "¿QUÉ SE CONECTA POR XLR?", a: ["CORRIENTE", "AUDIO Y SEÑAL DMX", "WI-FI"], correct: 1 },
    { q: "¿FUNCIÓN DE LAS BANDERAS (BARNDOORS)?", a: ["CAMBIAR COLOR", "RECORTAR Y DIRECCIONAR LUZ", "ENFRIAR"], correct: 1 }
  ]
};