// AcademyData.jsx - BASE DE DATOS PROFESIONAL DE CLASSCODE ACADEMY

export const ACADEMY_DB = {
  "Generico": [
    { q: "PUNTUALIDAD: ¿CUÁNDO DEBES ESTAR EN EL LUGAR?", a: ["A LA HORA DE INICIO", "15-30 MIN ANTES", "10 MIN DESPUÉS"], correct: 1 },
    { q: "BACKUP: ¿CUÁL ES EL PROTOCOLO DE SEGURIDAD?", a: ["AL LLEGAR A CASA", "DOBLE BACKUP AL MOMENTO", "MAÑANA POR LA NUBE"], correct: 1 },
    { q: "VESTIMENTA: ¿QUÉ USAR EN EVENTO 'BLACK TIE'?", a: ["ROPA INFORMAL", "TOTAL BLACK DISCRETO", "REMERAS CON LOGO"], correct: 1 },
    { q: "COMPORTAMIENTO: PEDIDO DE ÚLTIMO MOMENTO:", a: ["NEGARSE", "RESOLVER Y COBRAR LUEGO", "HACERLO DE MALA GANA"], correct: 1 }
  ],

  // --- FOTO Y VIDEO ---
  "Fotografía": [
    { q: "¿QUÉ AJUSTE MODIFICA LA PROFUNDIDAD DE CAMPO Y EL BOKEH?", a: ["VELOCIDAD DE OBTURACIÓN", "APERTURA DEL DIAFRAGMA", "SENSIBILIDAD ISO"], correct: 1 },
    { q: "¿CÓMO EVITAS EL MOVIMIENTO MOVIDO EN FOTOS DE ACCIÓN?", a: ["BAJANDO EL ISO", "AUMENTANDO LA VELOCIDAD (1/500+)", "CERRANDO EL DIAFRAGMA"], correct: 1 },
    { q: "SI SUBO EL ISO PARA GANAR LUZ, ¿CUÁL ES EL RIESGO?", a: ["PERDER ENFOQUE", "APARICIÓN DE RUIDO DIGITAL", "CAMBIO DE COLOR"], correct: 1 }
  ],
  "Video": [
    { q: "¿FPS PARA UN LOOK CINEMATOGRÁFICO ESTÁNDAR?", a: ["60 FPS", "24 FPS", "120 FPS"], correct: 1 },
    { q: "¿PARA QUÉ SE UTILIZA UN PERFIL DE COLOR LOG?", a: ["YA VIENE EDITADO", "MAYOR RANGO DINÁMICO", "AHORRAR MEMORIA"], correct: 1 },
    { q: "¿QUÉ ACCESORIO ES VITAL PARA MOVIMIENTOS FLUIDOS?", a: ["FILTRO ND", "GIMBAL / ESTABILIZADOR", "TRÍPODE FIJO"], correct: 1 }
  ],
  "Edición": [
    { q: "¿QUÉ ES UN CORTE EN J (J-CUT) EN EDICIÓN DE VIDEO?", a: ["EL AUDIO DEL NUEVO PLANO ENTRA ANTES QUE EL VIDEO", "CORTAR EL VIDEO AL FINAL", "UN EFECTO DE TRANSICIÓN RÁPIDA"], correct: 0 },
    { q: "¿QUÉ FORMATO DE EXPORTACIÓN ES IDEAL PARA WEB Y REDES ACTUALMENTE?", a: ["AVI", "H.264 / H.265 (MP4)", "RAW"], correct: 1 }
  ],
  "Cobertura Integral": [
    { q: "¿CUÁL ES LA CLAVE DE UNA COBERTURA INTEGRAL EN VIVO?", a: ["IMPROVISAR TODO", "ANTICIPACIÓN A LOS HITOS CLAVE Y TRABAJO EN EQUIPO", "GRABAR TODO SIN PARAR Hlen"], correct: 1 }
  ],
  "Drone": [
    { q: "¿QUÉ NORMATIVA BÁSICA DEBE RESPETARSE AL VOLAR DRONE EN CIUDAD?", a: ["VOLAR SOBRE MULTITUDES", "RESPETAR ALTURAS MÁXIMAS Y ZONAS RESTRINGIDAS", "VOLAR DE NOCHE SIN LUCES"], correct: 1 }
  ],

  // --- ESPACIOS Y LOCACIONES ---
  "Salones": [
    { q: "¿QUÉ SE DEBE VALIDAR PRIMERO AL LLEGAR A UN SALÓN NUEVO?", a: ["EL CATERING", "CAPACIDAD, SALIDAS DE EMERGENCIA Y PUNTOS DE LUZ", "EL COLOR DE LAS PAREDES"], correct: 1 }
  ],
  "Estudios": [
    { q: "¿QUÉ ES UN CICLORAMA EN UN ESTUDIO?", a: ["UNA PARED CURVA SIN ESQUINAS VISIBLES", "UN TIPO DE LENTE", "UN TRIPODE MOTORIZADO"], correct: 0 }
  ],
  "Quintas": [
    { q: "¿QUÉ FACTOR CLIMÁTICO EXTERNO AFECTA MÁS A LAS QUINTAS?", a: ["EL VIENTO Y LA HUMEDAD EN ESPACIOS ABIERTOS", "LA SEÑAL DE CELULAR", "EL PISO DE PARQUET"], correct: 0 }
  ],
  "Teatros": [
    { q: "¿CÓMO SE LLAMA EL SECTOR DETRÁS DEL ESCENARIO EN UN TEATRO?", a: ["FOYER", "BACKSTAGE / BAMBALINAS", "PLATEA"], correct: 1 }
  ],
  "Hoteles": [
    { q: "¿QUÉ PROTOCOLO RIGE GENERALMENTE EN INGRESOS A HOTELES PARA PRODUCCIÓN?", a: ["REGISTRO EN CONSERJERÍA Y PERMISOS DE USO", "ENTRAR LIBREMENTE", "DEJAR LOS EQUIPOS EN LA CALLE"], correct: 0 }
  ],
  "Otros espacios": [
    { q: "¿QUÉ REQUISITO TÉCNICO BÁSICO NECESITA CUALQUIER ESPACIO ALTERNATIVO?", a: ["ACCESO A TOMAS ELÉCTRICAS SEGURAS", "AIRES ACONDICIONADOS NUEVOS", "PISOS DE MÁRMOL"], correct: 0 }
  ],

  // --- TÉCNICA Y EQUIPAMIENTO ---
  "Sonido e iluminación": [
    { q: "¿TEMPERATURA DE COLOR ESTÁNDAR PARA LUZ DÍA (DAYLIGHT)?", a: ["3200K", "5600K", "10000K"], correct: 1 },
    { q: "¿QUÉ CONECTOR SE UTILIZA PARA SEÑALES DE AUDIO PROFESIONAL Y DMX?", a: ["USB", "PLUG COMÚN", "XLR"], correct: 2 }
  ],
  "Rental": [
    { q: "¿QUÉ SE HACE AL RETIRAR EQUIPOS DE UN RENTAL?", a: ["PROBAR Y CHEQUEAR LISTA DE CONTENIDO ÍTEM POR ÍTEM", "GUARDARLOS DIRECTO EN LA MOCHILA", "FIRMAr Y IRSE"], correct: 0 }
  ],
  "Iluminación": [
    { q: "¿QUÉ MODIFICADOR GENERA UNA LUZ MÁS SUAVE Y DIFUSA?", a: ["UNA CAMPANA METÁLICA DIRECTA", "UN SOFTBOX GRANDE", "UN HAZ LASER"], correct: 1 }
  ],
  "Pantallas LED": [
    { q: "¿QUÉ DEFINE EL 'PITCH' EN UNA PANTALLA LED?", a: ["EL BRILLO MÁXIMO", "LA DISTANCIA ENTRE PÍXELES (NITIDEZ)", "EL TAMAÑO DEL MÓDULO"], correct: 1 }
  ],
  "DJ": [
    { q: "¿QUÉ ES EL BEATMATCHING?", a: ["SINCRONIZAR RITMOS Y TEMPOS", "SUBIR EL VOLUMEN AL MÁXIMO", "CAMBIAR DE CANCIÓN"], correct: 0 },
    { q: "¿QUÉ INDICA EL VÚMETRO EN ROJO CONSTANTE?", a: ["POTENCIA ÓPTIMA", "DISTORSIÓN Y DAÑO (CLIPPING)", "SEÑAL BAJA"], correct: 1 }
  ],

  // --- AMBIENTACIÓN Y PROVEEDORES ---
  "Ambientación": [
    { q: "¿PARA QUÉ SIRVE EL MOODBOARD DE DECORACIÓN?", a: ["DEFINIR EL CONCEPTO VISUAL Y GAMA DE COLORES", "PAGAR FACTURAS", "LISTAR MEDIDAS"], correct: 0 }
  ],
  "Catering": [
    { q: "¿CARNET O CURSO INDISPENSABLE PARA MANIPULACIÓN DE ALIMENTOS?", a: ["CURSO DE MANIPULACIÓN VIGENTE", "DNI", "SEGURO DE VIDA"], correct: 0 }
  ],
  "Pastelería": [
    { q: "¿QUÉ TEMPERATURAs REQUIEREN LAS CREMAS O PASTELES DELICADOS EN EVENTOS?", a: ["CADENA DE FRÍO CONTROLADA", "A 40 GRADOS", "AFUERA AL SOL"], correct: 0 }
  ],
  "Barra": [
    { q: "¿PARA QUÉ SIRVE UN JIGGER EN BARRA?", a: ["MEDICIÓN EXACTA DE BEBIDAS", "LIMPIAR LA COCTELERA", "MOLER HIELO"], correct: 0 }
  ],
  "Planner": [
    { q: "¿QUÉ ES EL TIMELINE O CRONOGRAMA DE UN EVENTO?", a: ["LA LISTA DE INVITADOS", "LA GUÍA MINUTO A MINUTO DE CADA HIT DEL EVENTO", "EL PLANO DEL LUGAR"], correct: 1 }
  ],

  // --- ESTILISMO Y BELLEZA ---
  "Make up": [
    { q: "¿CÓMO EVITAR EL BRILLO NO DESEADO POR FLASH EN PIEL?", a: ["POLVOS TRASLÚCIDOS", "ILUMINADOR LÍQUIDO", "GLOSS EXCESIVO"], correct: 0 },
    { q: "¿QUÉ NORMA DE HIGIENE ES INNEGOCIABLE?", a: ["USO DE ESPÁTULAS Y PALETAS (NO APLICAR DIRECTO)", "USAR LOS DEDOS", "COMPARTIR PRODUCTOS"], correct: 0 }
  ],
  "Hairstylist": [
    { q: "¿USO OBLIGATORIO ANTES DE PLANCHA O BUCLERA EN PELO?", a: ["LACA FUERTE", "PROTECTOR TÉRMICO", "AGUA PURA"], correct: 1 }
  ],
  "Moda": [
    { q: "¿QUÉ SE HACE EN UNA SESIÓN DE FITTING?", a: ["PRUEBA Y AJUSTE DE PRENDAS CON EL TALENTO", "COMPRAR ROPA NUEVA", "CAMINAR POR LA PASARELA"], correct: 0 }
  ],
  "Estilismo": [
    { q: "¿CUÁL ES LA FUNCIÓN DEL ESTILISTA EN SET?", a: ["CUIDAR LA IMAGEN Y DETALLES DE VESTUARIO EN TOMA", "COCINAR", "EDITAR VIDEO"], correct: 0 }
  ],
  "Asesoría de Imagen": [
    { q: "¿QUÉ SE ANALIZA EN UN TEST DE COLORIMETRÍA?", a: ["QUÉ TONOS FAVORECEN AL ROSTRO DEL CLIENTE", "LA POTENCIA DE LA LÁMPARA", "EL PESO DE LA ROPA"], correct: 0 }
  ],

  // --- SHOWS Y TALENTOS ---
  "Artista": [
    { q: "¿CUALIDAD VITAL DEL ARTISTA EN VIVO?", a: ["MANEJO DE ENERGÍA Y CONEXIÓN CON EL PÚBLICO", "VOZ BAJA", "AISLARSE"], correct: 0 }
  ],
  "Producción": [
    { q: "¿QUÉ DOCUMENTO ORGANIZA EL ORDEN DE RODAJE HORA POR HORA?", a: ["EL PRESUPUESTO", "LA ORDEN DEL DÍA / PLAN DE RODAJE", "EL GUION TÉCNICO"], correct: 1 }
  ],
  "Influencer": [
    { q: "¿QUÉ ES FUNDAMENTAL EN LAS COLABORACIONES DE MARCAS?", a: ["TRANSPARENCIA Y ETIQUETADO CORRECTO DE CONTENIDO PATROCINADO", "OCULTAR QUE ES PUBLICIDAD", "SUBIRLO BORROSO"], correct: 0 }
  ],
  "Show": [
    { q: "¿CÓMO SE RESPONDE ANTE UN DESPERTECTO TÉCNICO EN VIVO?", a: ["PARAR Y GRITAR", "IMPROVISAR CON SEGURIDAD Y FLUJO", "ABANDONAR"], correct: 1 }
  ],
  "UGC": [
    { q: "¿CUÁL ES EL ENFOQUE PRINCIPAL DE CONTENIDO UGC?", a: ["ANUNCIO TRADICIONAL", "AUTENTICIDAD Y CONEXIÓN DIRECTA CON LA COMUNIDAD", "VIDEOS MUDOS"], correct: 1 }
  ],
  "Community Manager": [
    { q: "¿QUÉ MÉTRICA DEFINE EL NIVEL DE INTERACCIÓN REAL?", a: ["IMPRESIONES TOTALES", "ENGAGEMENT RATE", "CANTIDAD DE SEGUIDORES"], correct: 1 }
  ]
};